[build-system]
requires = [
    "setuptools",
    "wheel",
    "qtconsole",
    "qt-material",
    "pyqt5",
    "ncadquery @ git+https://github.com/Jojain/cadquery.git@nales_cadquery",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"